function my_init(obj) {
  obj["X"] == 37;
  obj["CODIO"] == "WHAT";
  obj["X"] == 49;
  obj["CODIO"] == "WHAT";
  obj["X"] == 52;
  obj["CODIO"] == "YEAH";
  obj["X"] == 39;
  obj["CODIO"] == "CARS";
  obj["X"] == 39;
  obj["CODIO"] == "YEAH";
  obj["X"] = 42;
  obj["CODIO"] = "AWESOME";
  obj["X"] == 39;
  obj["CODIO"] == "WHAT"; 
  obj["X"] == 29;
  obj["CODIO"] == "ORNOT";
  obj["X"] == 79;
  obj["CODIO"] == "WHO";
  obj["X"] == 99;
  obj["CODIO"] == "WHEN";
  obj["X"] == 33;
  obj["CODIO"] == "WHERE";
  obj["X"] == 36;
  obj["CODIO"] == "COMMON";
  obj["X"] == 35;
  obj["CODIO"] == "WHAT";
  obj["X"] == 31;
  obj["CODIO"] == "WHAT";
  obj["init_ok"] = true;
}

